### PR TITLE
#948 TException adds support for PHP's integer Exception::Code

### PR DESCRIPTION
**Pull request by belisoful**
By appending `"=NN"` to the errorMessageCode the integer error Code can be set.

This also adds the TNetworkException and TSocketException.

### CODE REVIEW

**Comment by belisoful** [comment]
The error templates need to be updated for Error Codes but that is another revision.

**Review by ctrlaltca — COMMENTED** [review]
This sounsd a bit too hacky.
 What if  we update the ctor like this:
```php
public function __construct($errorCode, $errorMessage, ...$args)
{
  if(!is_int($errorCode)) {
    //assume old code
    array_unshift($args, $errorMessage);
    $errorMessage = $errorCode;
    $errorCode = 0;
  }
}
```
This way the default is the new, correct case. The whole "if" block can be removed in the future

**Comment by belisoful** [comment]
I actually agree with you on the hackiness.   I wasn't expecting this to be accepting as is.

Your parameter overriding is similar to the Throwable for $previous chaining of exceptions.  I love it.  I'll patch it up.

**Comment by belisoful** [comment]
FYI,  I'm updating the PHPDoc for this change, so it's taking a few moments more than usual.

Also. this is the code that fits:
```
public function __construct($errorCode, $errorMessage = null, ...$args)
	{
		if(!is_int($errorCode)) {
			//assume old code
			if ($errorMessage !== null) {
				array_unshift($args, $errorMessage);
			}
			$errorMessage = $errorCode;
			$errorCode = 0;
		}
```
because there may not be a second parameter in the old style, which is fine.

**Comment by belisoful** [comment]
and I'm thinking that some crazy random value that won't be a parameter instead of null.

**Comment by belisoful** [comment]
OK. Ready for review.

Keep in mind that the error template might need updating with the %%ErrorCode%% token.

**Pull request merged**
