### PR TITLE
TComponent updated for TWeakCallableCollection and Behaviors can instance from array definitions

### PR DESCRIPTION
**Pull request by belisoful**
#728 TComponent uses TWeakCallableCollection to store event handlers, that way garbage collection can delete objects that still have active handlers.  Because those handlers are weak references, the object won't get stuck in garbage collection heck and refuse to GC.  TWeakCallableCollection is to prevent memory leaks due to event handlers causing circular and hard references.

#740 Yii has the ability to instance classes from a class name string, using a class instance, and from an array defining the class and additional properties.

These additional properties are important to future features to be added.

### CODE REVIEW

**Comment by belisoful** [comment]
The Unit Tests cover all changes made.  TComponent using TWeakCallableCollection tests both extensively, and the TComponentTest checks that behaviors are instancing correctly in all instances.

I hope this is easy to merge.  I thought this was going to be harder to revert things and go through it incrementally.

Also, I'm thinking of doing the new events after this. like TAuthManager::onLogon, TApplication::onInitComplete, and TPageService::onPrePageRun. Then the autogloballisten turned on for ApplicationComponents and some TComponent subclasses.

**Comment by belisoful** [comment]
The TComponentTest is changed to account for the error on the TComponent sub properties as well.  Isolating that one specific change in TComponentTest was difficult and is rolled into this check-in.   This new TComponent unit test will fail with the TComponent sub properties bug from before.

**Review by ctrlaltca — APPROVED** [review]
Code looks fine, now i'm up for some testing, especially with old php versions.
Even if I don't see a real cause why it should lead to any problem, better stay on the safe side

**Comment by belisoful** [comment]
Indeed.  safety first.

FYI, I have tested this on 7.3.11 and 7.4 (without and with, respectively, WeakReference), and both pass unit test.  The fallback behavior works efficiently.

**Comment by belisoful** [comment]
CTRL-ALT-C-A you are as much a code historian and librarian as much as an architect.

**Comment by ctrlaltca** [comment]
No regression found, I'd say this can be safely merged.

**Pull request merged**
