### PR TITLE
#848 TComponent Events support Closures and all callable types (with unit tests)

### PR DESCRIPTION
**Pull request by belisoful**
Unit tests to make sure Closures work.  Minor change to TComponent to support Closures.

### CODE REVIEW

**Comment by belisoful** [comment]
Support for Closures as event handlers was first built into TWeakCallableCollection, the collection of handlers. Then it was built into behavior events.  TComponent raiseEvent supporting closures is the last piece for integrating Closure into Prado as event handlers.

**Comment by belisoful** [comment]
are there any questions I can answer about this merge?

$handler is a callable so it must be a string, invokable object (aka Closure fits this category), or an array.

**Comment by ctrlaltca** [comment]
Sorry, this slipped under my radar, let me know when it's ready for review

**Comment by belisoful** [comment]
no problem.  I think the latest iteration is the best it'll be.  Nothing I was working on "required" it to be updated, thankfully.

**Pull request merged**
