### PR TITLE
#820 #818 #823 #821 #825 #826 #839 #822 are fixed

### LINKED ISSUE #820: TApplicationComponent::getClassFxEvents Performance Mode should cache all
Basically this line-  https://github.com/pradosoft/prado/blob/46bc20d67bfa655de2bbb05128d883c53161c3cf/framework/TApplicationComponent.php#L73

should read

`if ($mode === TApplicationMode::Performance || isset(Prado::$classMap[$baseClassName])) {`

This'll speed things up that much more for Performance mode.  Performance websites need their caches cleared for an upgrade so this should be fine.

### PR DESCRIPTION
**Pull request by belisoful**
#820 caches all fx methods in performance mode.
#818 removed phpdoc build up of "dy" methods from TCallChain.
#823 set TBehavior Enabled default to true, removed the setEnabled on initialize.
#821 checks for the property/event in the behavior before checking its isset().
#825 Adds TComponent::hasMethod replacement for method_exists that is behavior aware..
#826 Adds TComponent::getBehaviors.
#839 correctly detaches a behavior in the reverse order as attach.
#822 returns IClassBehavior or array of attached IBehavior[s] from TComponent::*tachClassBehavior.

with appropriate unit tests.

These can all be closed upon merge at this point.

There are some documentation updates as well.

I'm just going through the bugs, and thoroughly correcting and testing them.  So there will be more commits to fix more bugs.

However...   Given the dependency of #836 upon these bug fixes, it seemed prudent to merge these now.

Also, I want the merge to be manageable in size.  This is already big enough.

### CODE REVIEW

**Comment by ctrlaltca** [comment]
I'm sorry, but this is quite impossible to review.
Each fix should go in a  separate PR.
Feel free to merge anyway if you are confident.

**Comment by belisoful** [comment]
@ctrlaltca My humble apologies.  I tried keeping each bug fix to one commit for that reason.  there are a slew of minor tweaks and bug fixes that would take a while going one by one.   I have been keep the unit tests up to date and triple checked.   I wanted to get through a few of the bugs at once because of the dependency of the fixes from #836.

I haven't deviated from any stated intentions or code discussions/agreement.

I am very confident of this merge to this point, especially given the degree of time I've spent on the unit tests.  I will take responsibility for any issues of this merge, though I am confident there shouldn't be any.  Especially given the thoroughness of the unit tests.

From here on, I'll keep to your advice.  Also, thank you for your own confidence in me, these minor tweaks, and the unit tests.

I'll see if I can reset my branch after this merge so all the prior accepted commits are cleaned for further PRs.

**Comment by belisoful** [comment]
Many of these bugs are from my own improper coding.  I want to get them corrected ASAP.

**Comment by belisoful** [comment]
40% of the merge is new unit tests to ensure that the code update is properly functional.  10% is documentation update. FYI.

**Comment by belisoful** [comment]
@ctrlaltca If you want me to close the issues, I can, but if you want to verify issue each before closing as a way to check the work, I understand.   Having written the unit tests and triple checked them, I'll tell you that  the unit tests are solid.  IF you don't want to spend the time with it, let me know, I'll close the issues.

The other issues are more than just basic tweaks and why I think they definitely should be their own PR each.  I put them off for that reason and only focused on these [systemic-oriented patches].

Again, my humble apologies for making an unwieldy merge of minor bug fixes.   I got to working....  and working and working.

**Comment by belisoful** [comment]
I was hoping that keeping (for the most part) one commit per issue would keep things at least somewhat organized, no?

**Comment by ctrlaltca** [comment]
Don't worry, that's fine. I see the commits are well separated in the commit history, that's good for future troubleshooting.
Go on closing the issue, unfortunately I'm really short on time in these weeks; thank you for taking care of it.

**Comment by belisoful** [comment]
Enjoy the holidays.

**Pull request merged**
