### PR TITLE
[WIP] Doc updates; fix #964

### LINKED ISSUE #964: php-doc "<code>" converted to "```php"
or "```html" if the example is html.   also `</code>` needs the ending triple "`"

This is the kind of maintenance thing @ctrlaltca usually handles silently in the night.  ;)

### PR DESCRIPTION
**Pull request by ctrlaltca**
This PR replaces all < code > tags with markdown tags in phpdoc comments.
The Prism js library has been included in prado-phpdoc-template to enable syntax highlight.
It looks some more fixes are needed, eg. most link tags seems to be currently broken.

### CODE REVIEW

**Comment by belisoful** [comment]
Can you write a line or two about the issues you have encountered with `@link`?  and why the move to `@see`.  No problems, just trying to understand the bigger picture.

**Comment by belisoful** [comment]
Thank you for this description!  It help us understand your clearly clear view of this issue.

**Comment by belisoful** [comment]
I don't know if this helps.  Yii2 uses the double bracket `[[class]]` instead of `@see class`.   eg.

```phpdoc
 * BaseArrayHelper provides concrete implementation for [[ArrayHelper]].
 * Do not use BaseArrayHelper. Use [[ArrayHelper]] instead.
 ```

**Comment by ctrlaltca** [comment]
Yep, Yii uses its own implementation on top of phpDocumentor: https://github.com/yiisoft/yii2-apidoc

**Comment by ctrlaltca** [comment]
This is finally ready for merging, the results are already online at https://pradosoft.github.io/docs/manual

**Pull request merged**
